# action.yml
name: 'Tanzu Mission Control Apply'
description: 'tmcctl apply'
inputs:
  tmc-api-key:  # id of input
    description: 'TMC API Key'
    required: true       
runs:
  using: 'docker'  
  image: 'docker://docker.io/bmoussaud/tmc-gitops-demo:0.0.3'
  args:
    - ${{ inputs.tmc-api-key }}

  