# action.yml
name: 'Tanzu Mission Control Apply'
description: 'tmcctl apply'
inputs:
  day-of-the-week:  # id of input
    description: 'Day of the week'
    required: true   
    default: Monday 
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.day-of-the-week }}
    - ${{ secrets.TMC_API_TOKEN }}
  