fullName:
  name: bmoussaud-ops
meta:  
  description: My Cluster Group for ops.
  labels: 
    owner: bmoussaud
    country: france
    env: production
type:
  kind: ClusterGroup
  package: vmware.tanzu.manage.v1alpha1.clustergroup
  version: v1alpha1