on: [push]

jobs:
  tmc_ctl_apply_job:
    runs-on: ubuntu-latest
    name: TMC Gitops apply
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: tmc apply....
        uses: ./ # Uses an action in the root directory
        id: apply
        with:          
          tmc-api-key: ${{ secrets.TMC_API_TOKEN}}      